title: "Montajes Eléctricos Rebato Panadero"
description: "Empresa de instalaciones eléctricas y automatismos"
url: "https://github.com/B4mb0o0"     # sin barra al final
baseurl: "/montajesElectricosRP"        # *nombre exacto* de tu repositorio
lang: es